/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lilic
 */
public class PesoPessoasPlanetas extends javax.swing.JFrame {

    /**
     * Creates new form PesoPessoasPlanetas
     */
    public PesoPessoasPlanetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnMercurio = new javax.swing.JButton();
        btnVenus = new javax.swing.JButton();
        btnMarte = new javax.swing.JButton();
        btnJupiter = new javax.swing.JButton();
        btnSaturno = new javax.swing.JButton();
        btnUrano = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblPlaneta = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Peso na Terra (kg):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Selecione o Planeta:");

        btnMercurio.setText("Mercúrio");
        btnMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMercurioActionPerformed(evt);
            }
        });

        btnVenus.setText("Vênus");
        btnVenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenusActionPerformed(evt);
            }
        });

        btnMarte.setText("Marte");
        btnMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarteActionPerformed(evt);
            }
        });

        btnJupiter.setText("Júpiter");
        btnJupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJupiterActionPerformed(evt);
            }
        });

        btnSaturno.setText("Saturno");
        btnSaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaturnoActionPerformed(evt);
            }
        });

        btnUrano.setText("Urano");
        btnUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUranoActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPlaneta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMercurio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVenus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMarte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJupiter, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaturno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUrano, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMercurio)
                        .addGap(18, 18, 18)
                        .addComponent(btnVenus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMarte)
                        .addGap(18, 18, 18)
                        .addComponent(btnJupiter))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaturno)
                        .addGap(18, 18, 18)
                        .addComponent(btnUrano)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMercurioActionPerformed
        // TODO add your handling code here:
        double n = Double.parseDouble(lblText.getText());
        double s = (double) ((n/10) * 03.7);
        lblResult.setText(Double.toString(s));
        lblPlaneta.setText("Seu peso em Mercurio é");
    }//GEN-LAST:event_btnMercurioActionPerformed

    private void btnVenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenusActionPerformed
        // TODO add your handling code here:
        double n = Double.parseDouble(lblText.getText());
        double s = (double) ((n/10) * 08.8);
        lblResult.setText(Double.toString(s));
        lblPlaneta.setText("Seu peso em Venus é");
    }//GEN-LAST:event_btnVenusActionPerformed

    private void btnMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarteActionPerformed
        // TODO add your handling code here:
        double n = Double.parseDouble(lblText.getText());
        double s = (double) ((n/10) * 03.8);
        lblResult.setText(Double.toString(s));
        lblPlaneta.setText("Seu peso em Marte é");
    }//GEN-LAST:event_btnMarteActionPerformed

    private void btnJupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJupiterActionPerformed
        // TODO add your handling code here:
        double n = Double.parseDouble(lblText.getText());
        double s = (double) ((n/10) * 26.4);
        lblResult.setText(Double.toString(s));
        lblPlaneta.setText("Seu peso em Jupiter é");
    }//GEN-LAST:event_btnJupiterActionPerformed

    private void btnSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaturnoActionPerformed
        // TODO add your handling code here:
        double n = Double.parseDouble(lblText.getText());
        double s = (double) ((n/10) * 11.5);
        lblResult.setText(Double.toString(s));
        lblPlaneta.setText("Seu peso em Saturno é");
    }//GEN-LAST:event_btnSaturnoActionPerformed

    private void btnUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUranoActionPerformed
        // TODO add your handling code here:
        double n = Double.parseDouble(lblText.getText());
        double s = (double) ((n/10) * 11.7);
        lblResult.setText(Double.toString(s));
        lblPlaneta.setText("Seu peso em Urano é");
    }//GEN-LAST:event_btnUranoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        lblText.setText("");
        lblResult.setText("");
        lblPlaneta.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesoPessoasPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesoPessoasPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesoPessoasPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesoPessoasPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesoPessoasPlanetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJupiter;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMarte;
    private javax.swing.JButton btnMercurio;
    private javax.swing.JButton btnSaturno;
    private javax.swing.JButton btnUrano;
    private javax.swing.JButton btnVenus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPlaneta;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField lblText;
    // End of variables declaration//GEN-END:variables
}
